### ISSUE TITLE
How to Compile a Portable Binary

### ISSUE THREAD

**Issue by TheRealMrWicked** [martinetd/samloader#3]
I would like to make a binary (.exe) of this project that can be taken from one computer to another.

If I move the exe created from the pip3 installation to another computer that doesnt work, and pyinstaller does not work, the exe always fails.

Can you help me with this issue?

Thanks in Advance

- MrWicked

**Comment by martinetd** [comment]
[pyinstaller](https://pyinstaller.org/en/stable/) does seem to be the way to go for windows, but I don't have any windows machine around to test so I won't be able to help with this, sorry.
FWIW it does work on linux (in a virtualenv, with this repo checked out in the ./samloader directory)
```
$ virtualenv t
$ ./t/bin/python3 -m pip install ./samloader
$ ./t/bin/python3 -m pip install pyinstaller
$ ./t/bin/pyinstaller  ./t/bin/samloader
$ ./dist/samloader/samloader -m XXX -r XXX checkupdate
<correctly ran>
```

(For linux/mac there also seems to be another project, [portable-python](https://pypi.org/project/portable-python/), but I didn't test it either)

**Comment by RealMrWicked** [comment]
Thank you so much for your help and time.
