### ISSUE TITLE
FUS and decryption keys need updating

### ISSUE THREAD

**Issue by TheRealMrWicked** [martinetd/samloader#4]
Samsung made some recent changes preventing downloads since the latest smart switch update, both [Frija](https://github.com/SlackingVeteran/frija/releases/tag/v2.0.23357.1) and [Bifrost](https://github.com/zacharee/SamloaderKotlin/releases/tag/1.16.3) have been updated and work properly now.

See [this commit](https://github.com/zacharee/SamloaderKotlin/commit/e0766d729e9b7640793b26ade4f3a0e8af1752d8) from Bifrost for exactly what I am talking about.

I am making the issue just to notify you of the issue.

Thank you - MrWicked

**Comment by martinetd** [comment]
Thanks for the heads up!

I've shamlessly stole from that commit and opened #5 -- a quick local test shows no problem (confirmed I can't download with current version and now can with this patch), I'll merge it tomorrow morning unless someone yells at me.

I've added a reported-by with your github @TheRealMrWicked handle as I'm too lazy to try to dig for something more tangible, please tell me what you'd like there and I'll update that line.

**Comment by RealMrWicked** [comment]
I have done a test of my own and it appears to work as well, I'm closing this issue now, if needed we can further discuss in the PR.

Thank you for your help, much appreciated.
